name: Deploy to IPFS via Pinata
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install packages
        run: npm i
      - name: Build project
        run: npm run build
      - name: Deploy to IPFS
        id: deploy_IPFS
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: 'My IPFS Project'
          path: './dist'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
          remove-old: true
      - name: Log Deploy to IPFS
        run: |
          echo "Deployed Hash: ${{ steps.deploy_IPFS.outputs.HASH }}" &&
          echo "CID=${{ steps.deploy_IPFS.outputs.HASH }}" >> $GITHUB_ENV
      - name: Blockchain call
        run: |
          node utils/proposeVersion.js
        env: 
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          CID: ${{ steps.deploy_IPFS.outputs.HASH }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PROJECT_ID: "1"
          VERSION_NAME: "V0.0.1"
          FRONT_PROOF_CONTRACT_ADDRESS: "0xDb6290a754002d24Fc2A91d5f3c9A98aCd5c554d"

